### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by MartinWeczerek** [jaburns/NintendoSpy#62] opened 2019-05-26 16:06 UTC
I ran into the issue of not getting my generic controller detected, because NintendoSpy always looks only for the first plugged in controller. I saw this [commit](https://github.com/jaburns/NintendoSpy/issues/4) but realized the latest build is quite older then that.

Is it possible to get a new release with the latest features out? Or am I missing here something?

**Comment by jaburns** [comment] 2019-05-26 21:04
This is a duplicate of #38. The binaries are quite old, it's best to build from source. I'd compile it and push the release myself, but I don't have a device to test with at the moment, so I'd prefer a pull request from someone who's built and used it recently.

**Closed by jaburns** 2019-05-26 21:04 UTC
